### ISSUE TITLE
[1.18] Tracking data - GriefDefender

### ISSUE THREAD

**Issue by muriplz** [IzzelAliz/Arclight#984]
### I have confirmed that ...

- [ ] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Forge
- [X] unable to reproduce in Spigot

### Arclight version

arclight-1.18.2-1.0.8-e80a33d

### OS & Java versions

1.17

### Plugins and Mods

```raw
Create mod + Flywheel

Plugins: GriefDefender + Luckperms
```

### Description

Using Create mod + Arclight. Create mod has a fakeplayer block that is called "Deployer". When this fakeplayer block is moved by any Create mod feature, the tracking data in world/data/ is never updated, therefore it's a huge risk for protection for anyone using this mod + Arclight, as the source player for the fakeplayer is lost when the fakeplayer is moved. 

If the deployer is moved by vanilla feature, such as pistons, the source player does mantain

### Step to reproduce

1. Make a minecart contraption (rails + cart assembler + deployer + minecart)
2. Give 64 blocks to the Deployer (right clicking the hand)
3. use /gddebug record
4. give a redstone signal to the cart assembler and make the minecart contraption move
5. use /gddebug paste

Result: the deployer won't have an "owner", only where the deployer was first placed. Due to the tracking data never updating, GriefDefender still thinks the deployer didnt move

**Comment by IzzelAliz** [comment]
I don't know what your tracking data here refers to. Vanilla doesn't seems to have a kind of tracking data of placed block owners.

**Comment by muriplz** [comment]
GriefDefender Tracking data. It's Blood's plugin the one that takes the data into the **world/data/griefdefender/** folder. He said the issue is on Hybrid's side.
